# Generated by Django 3.2.4 on 2021-06-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Tran Quoc Duy', max_length=200),
            preserve_default=False,
        ),
    ]
